const express = require("express");
const createPost = require("../controllers/createPost");
const userFeed = require("../controllers/userFeed");
const viewUserPosts = require("../controllers/viewUserPosts");
const { likePost, unlikePost } = require("../controllers/likePost");
const jwtAuth = require("../middlewares/jwtAuth");
const router = express.Router();
router.get("/", jwtAuth, userFeed);
router.get("/:userId", jwtAuth, viewUserPosts);
router.post("/create", jwtAuth, createPost);
router.post("/like", jwtAuth, likePost);
router.post("/unlike", jwtAuth, unlikePost);
module.exports = router;
